on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  msrv:
    runs-on: swsnr-rust
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: echo "RUSTUP_TOOLCHAIN="$(cargo +stable metadata --no-deps --format-version 1 | jq -r '.packages | map(select(.name == "wol")) | first | .rust_version')"" >> "$FORGEJO_ENV"
      - run: echo "$RUSTUP_TOOLCHAIN"
      - run: cargo build --locked --all-features
      - run: cargo test --locked --all-features

  lint:
    runs-on: swsnr-rust
    env:
      RUSTUP_TOOLCHAIN: stable
    steps:
      - run: rustup update
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo deny --all-features --locked check
      - run: cargo fmt -- --check
      - run: cargo vet --locked

  stable:
    runs-on: swsnr-rust
    env:
      RUSTUP_TOOLCHAIN: stable
    steps:
      - run: rustup update
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo build --locked
      - run: cargo build --locked --features cli
      - run: cargo build --locked --all-features
      - run: cargo clippy --locked --all-features --all-targets
      - run: cargo test --locked --all-features
      - run: cargo doc --locked
