
# cargo-vet audits file

[[audits.heck]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "0.4.1 -> 0.5.0"
notes = "These changes to do not use an unsafe code, and do nto make use of any ambient capabilities."

[[audits.macaddr]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
version = "1.0.1"
notes = """
crate forbids unsafe code, and does not use ambient capabilities (no network, no filesystem access, etc.).
Parsing code is well-tested, and fuzzed.
"""

[[trusted.anstream]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-16"
end = "2026-03-25"

[[trusted.anstyle]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-05-18"
end = "2026-03-25"

[[trusted.anstyle-parse]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-08"
end = "2026-03-25"

[[trusted.anstyle-query]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-04-13"
end = "2026-03-25"

[[trusted.anstyle-wincon]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-08"
end = "2026-03-25"

[[trusted.clap]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2021-12-08"
end = "2026-03-25"

[[trusted.clap_builder]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-28"
end = "2026-03-25"

[[trusted.clap_derive]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2021-12-08"
end = "2026-03-25"

[[trusted.clap_lex]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-04-15"
end = "2026-03-25"

[[trusted.colorchoice]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-04-13"
end = "2026-03-25"

[[trusted.is_terminal_polyfill]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2024-05-02"
end = "2026-03-25"

[[trusted.syn]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2026-03-25"

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2021-11-15"
end = "2026-03-25"

[[trusted.windows-targets]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2022-09-09"
end = "2026-03-25"

[[trusted.windows_aarch64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2022-09-01"
end = "2026-03-25"

[[trusted.windows_aarch64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2021-11-05"
end = "2026-03-25"

[[trusted.windows_i686_gnu]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2021-10-28"
end = "2026-03-25"

[[trusted.windows_i686_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2024-04-02"
end = "2026-03-25"

[[trusted.windows_i686_msvc]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2021-10-27"
end = "2026-03-25"

[[trusted.windows_x86_64_gnu]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2021-10-28"
end = "2026-03-25"

[[trusted.windows_x86_64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2022-09-01"
end = "2026-03-25"

[[trusted.windows_x86_64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2021-10-27"
end = "2026-03-25"
