
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.swsnr]
url = "https://raw.githubusercontent.com/swsnr/rust-supply-chain/refs/heads/main/audits.toml"

[policy.wol]
audit-as-crates-io = false

[[exemptions.terminal_size]]
# Unix/linux code looks safe, but I don't feel like checking the unsafe Windows code
version = "0.4.2"
criteria = "safe-to-deploy"
