name: Release

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: '${{ secrets.CARGO_REGISTRY_TOKEN }}'
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo publish --no-verify

  vendor-dependencies:
    permissions:
      id-token: write
      contents: read
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo --version
      - run: tar --version
      - run: zstd --version
      - run: echo "${GITHUB_SHA}"
      # Generate a reproducible vendor bundle
      - run: env LC_ALL=C TZ=UTC0 echo "timestamp=$(git show --quiet --date='format-local:%Y-%m-%dT%H:%M:%SZ' --format="%cd" "${GITHUB_SHA}")" >> "$GITHUB_OUTPUT"
        id: timestamp
      - run: cargo vendor --locked
      - run: env LC_ALL=C tar --numeric-owner --owner 0 --group 0 --sort name --mode='go+u,go-w' --format=posix --pax-option=exthdr.name=%d/PaxHeaders/%f --pax-option=delete=atime,delete=ctime --mtime="${{ steps.timestamp.outputs.timestamp }}" -c -f "wol-${{ github.ref_name }}-vendor.tar.zst" --zstd vendor
      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: wol-${{ github.ref_name }}-vendor.tar.zst
      - uses: actions/upload-artifact@v4
        with:
          name: wol-${{ github.ref_name }}-vendor.tar.zst
          path: wol-${{ github.ref_name }}-vendor.tar.zst

  git-archive:
    permissions:
      id-token: write
      contents: read
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: env LC_ALL=C TZ=UTC0 git archive --format tar --prefix 'wol-${{ github.ref_name }}/' --output 'wol-${{ github.ref_name }}.tar' "${{ github.sha }}"
      - run: zstd 'wol-${{ github.ref_name }}.tar'
      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'wol-${{ github.ref_name }}.tar.zst'
      - uses: actions/upload-artifact@v4
        with:
          name: wol-${{ github.ref_name }}.tar.zst
          path: wol-${{ github.ref_name }}.tar.zst

  windows-binary:
    permissions:
      id-token: write
      contents: read
      attestations: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --all-features --locked --release
      - run: 7z a "wol-${{ github.ref_name }}-windows-x86_64.zip" target/release/wol.exe
      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'wol-${{ github.ref_name }}-windows-x86_64.zip'
      - uses: actions/upload-artifact@v4
        with:
          name: wol-${{ github.ref_name }}-windows-x86_64.zip
          path: wol-${{ github.ref_name }}-windows-x86_64.zip

  linux-binary:
    permissions:
      id-token: write
      contents: read
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --all-features --locked --release
      - run: mkdir wol-${{ github.ref_name }}-linux-x86_64
      - run: mv -t wol-${{ github.ref_name }}-linux-x86_64 target/release/wol
      - run: env LC_ALL=C tar --numeric-owner --owner 0 --group 0 --sort name --mode='go+u,go-w' --format=posix --pax-option=exthdr.name=%d/PaxHeaders/%f --pax-option=delete=atime,delete=ctime -c -f "wol-${{ github.ref_name }}-linux-x86_64.tar.zstd" --zstd wol-${{ github.ref_name }}-linux-x86_64
      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'wol-${{ github.ref_name }}-linux-x86_64.tar.zst'
      - uses: actions/upload-artifact@v4
        with:
          name: wol-${{ github.ref_name }}-linux-x86_64.tar.zst
          path: wol-${{ github.ref_name }}-linux-x86_64.tar.zst

  create-release:
    runs-on: ubuntu-latest
    needs:
      - git-archive
      - vendor-dependencies
      - windows-binary
      - linux-binary
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          merge-multiple: false
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ./*.tar.zst
            ./*.zip
